balance: "Social Media Marketing and Advertising\r\nWebsite Development\r\nDigital Advertising and Campaign Planning\r\nSEO"
contact: "0247899821"
country: "ghana"
dob: "2001-02-03"
email: "kasante@gmail.com"
fname: "Kwame"
gender: "male"
laptop: "yes"
lname: "Asante"
oname: ""
programme: "Computer Science"
reason: "Social Media Marketing and Advertising\r\nWebsite Development\r\nDigital Advertising and Campaign Planning\r\nSEO"
scholarship: "yes"
school: "ashesi"
statement: "Social Media Marketing and Advertising\r\nWebsite Development\r\nDigital Advertising and Campaign Planning\r\nSEO"
year: "3"